version: "3"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    environment:
      FRONTEND_HOST: "http://localhost:3000"
    ports:
      - 3001:3001
    entrypoint: yarn start:dev

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    environment:
      BACKEND_HOST: "http://localhost:3001"
    ports:
      - 3000:3000
    entrypoint: yarn start
    stdin_open: true
